-- Initial schema.
--
-- Flyway owns the schema; Hibernate only validates it at startup. Identifiers are generated by the
-- domain, so no column carries a DEFAULT: an entity must be valid and have an identity before it
-- ever reaches the database.
--
-- The CHECK constraints are a safety net, not the mechanism. Every rule that exists here also
-- exists in a service, which is what produces the business error. The two exceptions are the
-- unique indexes on the user email and on the ingredient name, where only the database can settle
-- the race, and where the services translate the violation instead.

CREATE TABLE app_user (
    id            uuid         PRIMARY KEY,
    email         varchar(254) NOT NULL,
    password_hash varchar(72)  NOT NULL,
    created_at    timestamptz  NOT NULL,
    CONSTRAINT ux_app_user_email UNIQUE (email)
);

CREATE TABLE ingredient (
    id         uuid        PRIMARY KEY,
    owner_id   uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name       varchar(80) NOT NULL,
    dimension  varchar(16) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_ingredient_dimension CHECK (dimension IN ('MASS', 'VOLUME', 'COUNT'))
);
CREATE UNIQUE INDEX ux_ingredient_owner_name ON ingredient (owner_id, lower(name));

CREATE TABLE recipe (
    id           uuid         PRIMARY KEY,
    owner_id     uuid         NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    title        varchar(120) NOT NULL,
    servings     integer      NOT NULL,
    status       varchar(16)  NOT NULL,
    created_at   timestamptz  NOT NULL,
    updated_at   timestamptz  NOT NULL,
    published_at timestamptz,
    archived_at  timestamptz,
    CONSTRAINT ck_recipe_servings CHECK (servings BETWEEN 1 AND 50),
    CONSTRAINT ck_recipe_status   CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_recipe_published_at CHECK ((status = 'DRAFT') = (published_at IS NULL)),
    CONSTRAINT ck_recipe_archived_at  CHECK ((status = 'ARCHIVED') = (archived_at IS NOT NULL))
);
CREATE INDEX ix_recipe_owner ON recipe (owner_id);

CREATE TABLE recipe_line (
    id            uuid    PRIMARY KEY,
    recipe_id     uuid    NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    line_index    integer NOT NULL,
    ingredient_id uuid    NOT NULL REFERENCES ingredient (id) ON DELETE RESTRICT,
    amount_milli  bigint  NOT NULL,
    CONSTRAINT ck_recipe_line_amount CHECK (amount_milli > 0 AND amount_milli <= 1000000000),
    -- Deferred, and the only two constraints in this schema that are. Replacing the content of a
    -- recipe deletes every line and inserts the new ones, and Hibernate flushes the inserts before
    -- the deletes, so the old rows and the new ones coexist in the middle of the transaction: a
    -- reused line index, or two lines swapping ingredients, would break an immediate constraint
    -- even though the state at commit is perfectly valid. The uniqueness of the email of an account
    -- and of an ingredient name are deliberately NOT deferred: their services translate the
    -- violation into a business error and need it to surface at the flush they control.
    CONSTRAINT ux_recipe_line_index      UNIQUE (recipe_id, line_index)     DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ux_recipe_line_ingredient UNIQUE (recipe_id, ingredient_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ix_recipe_line_ingredient ON recipe_line (ingredient_id);

CREATE TABLE pantry_item (
    id            uuid        PRIMARY KEY,
    owner_id      uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    ingredient_id uuid        NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    amount_milli  bigint      NOT NULL,
    version       bigint      NOT NULL,
    updated_at    timestamptz NOT NULL,
    CONSTRAINT ck_pantry_item_amount CHECK (amount_milli >= 0 AND amount_milli <= 1000000000),
    CONSTRAINT ux_pantry_item_owner_ingredient UNIQUE (owner_id, ingredient_id)
);

CREATE TABLE plan_entry (
    id           uuid        PRIMARY KEY,
    owner_id     uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    recipe_id    uuid        NOT NULL REFERENCES recipe (id) ON DELETE RESTRICT,
    planned_for  date        NOT NULL,
    servings     integer     NOT NULL,
    status       varchar(16) NOT NULL,
    version      bigint      NOT NULL,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL,
    cooked_at    timestamptz,
    cancelled_at timestamptz,
    CONSTRAINT ck_plan_entry_servings CHECK (servings BETWEEN 1 AND 50),
    CONSTRAINT ck_plan_entry_status   CHECK (status IN ('PLANNED', 'COOKED', 'CANCELLED')),
    CONSTRAINT ck_plan_entry_cooked_at    CHECK ((status = 'COOKED')    = (cooked_at IS NOT NULL)),
    CONSTRAINT ck_plan_entry_cancelled_at CHECK ((status = 'CANCELLED') = (cancelled_at IS NOT NULL))
);
CREATE INDEX ix_plan_entry_owner_date ON plan_entry (owner_id, planned_for);
CREATE INDEX ix_plan_entry_recipe     ON plan_entry (recipe_id);
